# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-01-20 08:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_auto_20170120_0801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='path',
            field=models.CharField(max_length=128, verbose_name='\u8def\u5f84'),
        ),
    ]
