# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-01-20 10:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_auto_20170120_0802'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taskconf',
            old_name='exc_user',
            new_name='default_user',
        ),
        migrations.AddField(
            model_name='taskconf',
            name='task_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='taskconf',
            name='user_action',
            field=models.CharField(choices=[('allow', 'allow'), ('deny', 'deny')], default='deny', max_length=32, verbose_name='\u6267\u884c\u7528\u6237\u9009\u62e9'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='taskconf',
            name='user_list',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='taskconf',
            name='timeout',
            field=models.IntegerField(default=120, verbose_name='\u8d85\u65f6\u65f6\u95f4'),
        ),
    ]
